'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Form_Main_Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SM64_ROM_Manager.Form_Main_Resources", GetType(Form_Main_Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Open ROM... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Button_OpenRom() As String
            Get
                Return ResourceManager.GetString("Button_OpenRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This ROM was modified by SM64 Editor and isn&apos;t compatible with SM64 ROM Manager. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Exception_RomWasUsedBySM64E() As String
            Get
                Return ResourceManager.GetString("Exception_RomWasUsedBySM64E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Successfully changed the size of bank 0x19. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_BankSizeChangedSuccess() As String
            Get
                Return ResourceManager.GetString("MsgBox_BankSizeChangedSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Size changed ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_BankSizeChangedSuccess_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_BankSizeChangedSuccess_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An error occurred while converting .m64 to .midi! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_ConvertToMidi_Failed() As String
            Get
                Return ResourceManager.GetString("MsgBox_ConvertToMidi_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die M64 to MIDI failed ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_ConvertToMidi_Failed_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_ConvertToMidi_Failed_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Successfully converted M64 to MIDI ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_ConvertToMidi_Succes() As String
            Get
                Return ResourceManager.GetString("MsgBox_ConvertToMidi_Succes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die M64 to MIDI success ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_ConvertToMidi_Succes_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_ConvertToMidi_Succes_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An error occurred while saving the sequence. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_ErrorSavingSequence() As String
            Get
                Return ResourceManager.GetString("MsgBox_ErrorSavingSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An error occurred while exporting the sequence as MIDI. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_ExportToMidi_Failed() As String
            Get
                Return ResourceManager.GetString("MsgBox_ExportToMidi_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export to MIDI ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_ExportToMidi_Failed_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_ExportToMidi_Failed_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The game name probably contains invalid characters. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_GameNameHasInvalidChars() As String
            Get
                Return ResourceManager.GetString("MsgBox_GameNameHasInvalidChars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The size is too small. The minimum size is {0}. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_InvalidBankSize() As String
            Get
                Return ResourceManager.GetString("MsgBox_InvalidBankSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid size ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_InvalidBankSize_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_InvalidBankSize_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This image does not have a valid size.&lt;br/&gt;The &lt;b&gt;recommended&lt;/b&gt;size is 248x248. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_InvalidBgImageSize() As String
            Get
                Return ResourceManager.GetString("MsgBox_InvalidBgImageSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid size ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_InvalidBgImageSize_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_InvalidBgImageSize_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The limit of possible music sequences in the original game is 127. Do you want to add more anyway? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_LimitSequenceCountReached() As String
            Get
                Return ResourceManager.GetString("MsgBox_LimitSequenceCountReached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Limit reached ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_LimitSequenceCountReached_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_LimitSequenceCountReached_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The maximum amount of areas a level can have is 8. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_MaxCountAreasReached() As String
            Get
                Return ResourceManager.GetString("MsgBox_MaxCountAreasReached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximum reached ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_MaxCountAreasReached_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_MaxCountAreasReached_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The maximum amount of possible music sequences has been reached! It is not possible to add any more. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_MaxSequenceCountReached() As String
            Get
                Return ResourceManager.GetString("MsgBox_MaxSequenceCountReached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximum reached ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_MaxSequenceCountReached_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_MaxSequenceCountReached_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The ROM will be prepared for use with SM64 ROM Manager. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_PrepaireRom() As String
            Get
                Return ResourceManager.GetString("MsgBox_PrepaireRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Prepare ROM ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_PrepaireRom_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_PrepaireRom_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The ROM can&apos;t be started. Make sure the path to the emulator is correct. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_RomCanNotBestarted() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomCanNotBestarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Launch Game ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_RomCanNotBestarted_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomCanNotBestarted_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The ROM was changed by an external program. Do you want to reload the ROM?&lt;br/&gt;&lt;br/&gt;Warning:&lt;br/&gt;When reloading the ROM, all unsaved changes will be lost! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_RomChanged() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ROM changes detected ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_RomChanged_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomChanged_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The opened ROM has been deleted.&lt;br/&gt;The program will close now. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_RomRemoved() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomRemoved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ROM deleted ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_RomRemoved_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomRemoved_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Your text exceeds the character limit! Please shorten it before saving the ROM. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_TextsOverLimit() As String
            Get
                Return ResourceManager.GetString("MsgBox_TextsOverLimit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Character limit exceeded ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_TextsOverLimit_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_TextsOverLimit_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An unknown error occurred while loading the ROM. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_UnknownErrorAtLoadingRom() As String
            Get
                Return ResourceManager.GetString("MsgBox_UnknownErrorAtLoadingRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Load ROM ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_UnknownErrorAtLoadingRom_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_UnknownErrorAtLoadingRom_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die There are unsaved changes to the ROM.&lt;br/&gt;Do you want to save before closing? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_UnsavedChanges() As String
            Get
                Return ResourceManager.GetString("MsgBox_UnsavedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unsaved changes ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_UnsavedChanges_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_UnsavedChanges_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die There are updated patches available for this ROM, which provide improvements and/or new features.&lt;br/&gt;It is &lt;u&gt;highly recommended&lt;/u&gt; to apply them.&lt;br/&gt;&lt;br/&gt;Do you want to apply the patches now? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_UpdatePatchesAvaiable() As String
            Get
                Return ResourceManager.GetString("MsgBox_UpdatePatchesAvaiable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New patches available ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MsgBox_UpdatePatchesAvaiable_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_UpdatePatchesAvaiable_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You must open a ROM first! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Notify_ShouldLoadRomFirst() As String
            Get
                Return ResourceManager.GetString("Notify_ShouldLoadRomFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculating space... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_CalculatingTextSpace() As String
            Get
                Return ResourceManager.GetString("Status_CalculatingTextSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Checking ROM... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_Checking() As String
            Get
                Return ResourceManager.GetString("Status_Checking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Creating new sequence... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_CreatingNewSequence() As String
            Get
                Return ResourceManager.GetString("Status_CreatingNewSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Creating text list... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_CreatingTextList() As String
            Get
                Return ResourceManager.GetString("Status_CreatingTextList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exporting Model Map... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_ExportingModel() As String
            Get
                Return ResourceManager.GetString("Status_ExportingModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exporting Sequence... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_ExportingSequence() As String
            Get
                Return ResourceManager.GetString("Status_ExportingSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Importing Sequence ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_ImportingSequence() As String
            Get
                Return ResourceManager.GetString("Status_ImportingSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading Level... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_LoadingLevel() As String
            Get
                Return ResourceManager.GetString("Status_LoadingLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading Model Map... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_LoadingModel() As String
            Get
                Return ResourceManager.GetString("Status_LoadingModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading Music... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_LoadingMusic() As String
            Get
                Return ResourceManager.GetString("Status_LoadingMusic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading ROM... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_LoadingRom() As String
            Get
                Return ResourceManager.GetString("Status_LoadingRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading text from ROM... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_LoadingTexts() As String
            Get
                Return ResourceManager.GetString("Status_LoadingTexts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_Ready() As String
            Get
                Return ResourceManager.GetString("Status_Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Saving ROM... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_SavingRom() As String
            Get
                Return ResourceManager.GetString("Status_SavingRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starting up... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Status_StartingUp() As String
            Get
                Return ResourceManager.GetString("Status_StartingUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Area ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_Area() As String
            Get
                Return ResourceManager.GetString("Text_Area", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Change level to overwrite ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_ChangeReplacingLevel() As String
            Get
                Return ResourceManager.GetString("Text_ChangeReplacingLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_Disabled() As String
            Get
                Return ResourceManager.GetString("Text_Disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invisible ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_Invisible() As String
            Get
                Return ResourceManager.GetString("Text_Invisible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Level {0}, Star {1} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_LevelStar() As String
            Get
                Return ResourceManager.GetString("Text_LevelStar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mist ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_Mist() As String
            Get
                Return ResourceManager.GetString("Text_Mist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New Length ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_NewLength() As String
            Get
                Return ResourceManager.GetString("Text_NewLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Secret Star ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_SecretStar() As String
            Get
                Return ResourceManager.GetString("Text_SecretStar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Position ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_StartPosition() As String
            Get
                Return ResourceManager.GetString("Text_StartPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Toxic Haze ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_ToxicHaze() As String
            Get
                Return ResourceManager.GetString("Text_ToxicHaze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_Unknown() As String
            Get
                Return ResourceManager.GetString("Text_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} of {1} used / {2} left ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_UsedOfMaxLeft() As String
            Get
                Return ResourceManager.GetString("Text_UsedOfMaxLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Water ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Text_Water() As String
            Get
                Return ResourceManager.GetString("Text_Water", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reload ROM ähnelt.
        '''</summary>
        Public Shared ReadOnly Property WarningBox_RomChanged_ReloadRom() As String
            Get
                Return ResourceManager.GetString("WarningBox_RomChanged_ReloadRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The ROM was changed by an external program. To reload the ROM click on &apos;Reload ROM&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property WarningBox_RomChanged_Text() As String
            Get
                Return ResourceManager.GetString("WarningBox_RomChanged_Text", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
