'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Form_Main_Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SM64_ROM_Manager.Form_Main_Resources", GetType(Form_Main_Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open ROM....
        '''</summary>
        Friend Shared ReadOnly Property Button_OpenRom() As String
            Get
                Return ResourceManager.GetString("Button_OpenRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This ROM was modified by SM64 Editor and isn&apos;t compatible with SM64 ROM Manager..
        '''</summary>
        Friend Shared ReadOnly Property Exception_RomWasUsedBySM64E() As String
            Get
                Return ResourceManager.GetString("Exception_RomWasUsedBySM64E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully changed the size of bank 0x19..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_BankSizeChangedSuccess() As String
            Get
                Return ResourceManager.GetString("MsgBox_BankSizeChangedSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Size changed.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_BankSizeChangedSuccess_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_BankSizeChangedSuccess_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while converting .m64 to .midi!.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_ConvertToMidi_Failed() As String
            Get
                Return ResourceManager.GetString("MsgBox_ConvertToMidi_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M64 to MIDI failed.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_ConvertToMidi_Failed_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_ConvertToMidi_Failed_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully converted M64 to MIDI.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_ConvertToMidi_Succes() As String
            Get
                Return ResourceManager.GetString("MsgBox_ConvertToMidi_Succes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M64 to MIDI success.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_ConvertToMidi_Succes_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_ConvertToMidi_Succes_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while saving the sequence..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_ErrorSavingSequence() As String
            Get
                Return ResourceManager.GetString("MsgBox_ErrorSavingSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while exporting the sequence as MIDI..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_ExportToMidi_Failed() As String
            Get
                Return ResourceManager.GetString("MsgBox_ExportToMidi_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export to MIDI.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_ExportToMidi_Failed_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_ExportToMidi_Failed_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The game name probably contains invalid characters..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_GameNameHasInvalidChars() As String
            Get
                Return ResourceManager.GetString("MsgBox_GameNameHasInvalidChars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The size is too small. The minimum size is {0}..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_InvalidBankSize() As String
            Get
                Return ResourceManager.GetString("MsgBox_InvalidBankSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid size.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_InvalidBankSize_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_InvalidBankSize_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This image does not have a valid size.&lt;br/&gt;The &lt;b&gt;recommended&lt;/b&gt;size is 248x248..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_InvalidBgImageSize() As String
            Get
                Return ResourceManager.GetString("MsgBox_InvalidBgImageSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid size.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_InvalidBgImageSize_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_InvalidBgImageSize_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The limit of possible music sequences in the original game is 127. Do you want to add more anyway?.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_LimitSequenceCountReached() As String
            Get
                Return ResourceManager.GetString("MsgBox_LimitSequenceCountReached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Limit reached.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_LimitSequenceCountReached_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_LimitSequenceCountReached_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The maximum amount of areas a level can have is 8..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_MaxCountAreasReached() As String
            Get
                Return ResourceManager.GetString("MsgBox_MaxCountAreasReached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum reached.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_MaxCountAreasReached_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_MaxCountAreasReached_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The maximum amount of possible music sequences has been reached! It is not possible to add any more..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_MaxSequenceCountReached() As String
            Get
                Return ResourceManager.GetString("MsgBox_MaxSequenceCountReached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum reached.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_MaxSequenceCountReached_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_MaxSequenceCountReached_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The ROM will be prepared for use with SM64 ROM Manager..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_PrepaireRom() As String
            Get
                Return ResourceManager.GetString("MsgBox_PrepaireRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prepare ROM.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_PrepaireRom_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_PrepaireRom_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The ROM can&apos;t be started. Make sure the path to the emulator is correct..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_RomCanNotBestarted() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomCanNotBestarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launch Game.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_RomCanNotBestarted_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomCanNotBestarted_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The ROM was changed by an external program. Do you want to reload the ROM?&lt;br/&gt;&lt;br/&gt;Warning:&lt;br/&gt;When reloading the ROM, all unsaved changes will be lost!.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_RomChanged() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ROM changes detected.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_RomChanged_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomChanged_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The opened ROM has been deleted.&lt;br/&gt;The program will close now..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_RomRemoved() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomRemoved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ROM deleted.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_RomRemoved_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_RomRemoved_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your text exceeds the character limit! Please shorten it before saving the ROM..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_TextsOverLimit() As String
            Get
                Return ResourceManager.GetString("MsgBox_TextsOverLimit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Character limit exceeded.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_TextsOverLimit_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_TextsOverLimit_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unknown error occurred while loading the ROM..
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_UnknownErrorAtLoadingRom() As String
            Get
                Return ResourceManager.GetString("MsgBox_UnknownErrorAtLoadingRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load ROM.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_UnknownErrorAtLoadingRom_Titel() As String
            Get
                Return ResourceManager.GetString("MsgBox_UnknownErrorAtLoadingRom_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are unsaved changes to the ROM.&lt;br/&gt;Do you want to save before closing?.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_UnsavedChanges() As String
            Get
                Return ResourceManager.GetString("MsgBox_UnsavedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsaved changes.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_UnsavedChanges_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_UnsavedChanges_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are updated patches available for this ROM, which provide improvements and/or new features.&lt;br/&gt;It is &lt;u&gt;highly recommended&lt;/u&gt; to apply them.&lt;br/&gt;&lt;br/&gt;Do you want to apply the patches now?.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_UpdatePatchesAvaiable() As String
            Get
                Return ResourceManager.GetString("MsgBox_UpdatePatchesAvaiable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New patches available.
        '''</summary>
        Friend Shared ReadOnly Property MsgBox_UpdatePatchesAvaiable_Title() As String
            Get
                Return ResourceManager.GetString("MsgBox_UpdatePatchesAvaiable_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You should load a ROM first..
        '''</summary>
        Friend Shared ReadOnly Property Notify_ShouldLoadRomFirst() As String
            Get
                Return ResourceManager.GetString("Notify_ShouldLoadRomFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculating space....
        '''</summary>
        Friend Shared ReadOnly Property Status_CalculatingTextSpace() As String
            Get
                Return ResourceManager.GetString("Status_CalculatingTextSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking ROM....
        '''</summary>
        Friend Shared ReadOnly Property Status_Checking() As String
            Get
                Return ResourceManager.GetString("Status_Checking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating new sequence....
        '''</summary>
        Friend Shared ReadOnly Property Status_CreatingNewSequence() As String
            Get
                Return ResourceManager.GetString("Status_CreatingNewSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating text list....
        '''</summary>
        Friend Shared ReadOnly Property Status_CreatingTextList() As String
            Get
                Return ResourceManager.GetString("Status_CreatingTextList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exporting Model Map....
        '''</summary>
        Friend Shared ReadOnly Property Status_ExportingModel() As String
            Get
                Return ResourceManager.GetString("Status_ExportingModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exporting Sequence....
        '''</summary>
        Friend Shared ReadOnly Property Status_ExportingSequence() As String
            Get
                Return ResourceManager.GetString("Status_ExportingSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importing Sequence.
        '''</summary>
        Friend Shared ReadOnly Property Status_ImportingSequence() As String
            Get
                Return ResourceManager.GetString("Status_ImportingSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Level....
        '''</summary>
        Friend Shared ReadOnly Property Status_LoadingLevel() As String
            Get
                Return ResourceManager.GetString("Status_LoadingLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Model Map....
        '''</summary>
        Friend Shared ReadOnly Property Status_LoadingModel() As String
            Get
                Return ResourceManager.GetString("Status_LoadingModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Music....
        '''</summary>
        Friend Shared ReadOnly Property Status_LoadingMusic() As String
            Get
                Return ResourceManager.GetString("Status_LoadingMusic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading ROM....
        '''</summary>
        Friend Shared ReadOnly Property Status_LoadingRom() As String
            Get
                Return ResourceManager.GetString("Status_LoadingRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading text from ROM....
        '''</summary>
        Friend Shared ReadOnly Property Status_LoadingTexts() As String
            Get
                Return ResourceManager.GetString("Status_LoadingTexts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready.
        '''</summary>
        Friend Shared ReadOnly Property Status_Ready() As String
            Get
                Return ResourceManager.GetString("Status_Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saving ROM....
        '''</summary>
        Friend Shared ReadOnly Property Status_SavingRom() As String
            Get
                Return ResourceManager.GetString("Status_SavingRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting up....
        '''</summary>
        Friend Shared ReadOnly Property Status_StartingUp() As String
            Get
                Return ResourceManager.GetString("Status_StartingUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Area.
        '''</summary>
        Friend Shared ReadOnly Property Text_Area() As String
            Get
                Return ResourceManager.GetString("Text_Area", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change level to overwrite.
        '''</summary>
        Friend Shared ReadOnly Property Text_ChangeReplacingLevel() As String
            Get
                Return ResourceManager.GetString("Text_ChangeReplacingLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disabled.
        '''</summary>
        Friend Shared ReadOnly Property Text_Disabled() As String
            Get
                Return ResourceManager.GetString("Text_Disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invisible.
        '''</summary>
        Friend Shared ReadOnly Property Text_Invisible() As String
            Get
                Return ResourceManager.GetString("Text_Invisible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level {0}, Star {1}.
        '''</summary>
        Friend Shared ReadOnly Property Text_LevelStar() As String
            Get
                Return ResourceManager.GetString("Text_LevelStar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mist.
        '''</summary>
        Friend Shared ReadOnly Property Text_Mist() As String
            Get
                Return ResourceManager.GetString("Text_Mist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Length.
        '''</summary>
        Friend Shared ReadOnly Property Text_NewLength() As String
            Get
                Return ResourceManager.GetString("Text_NewLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secret Star.
        '''</summary>
        Friend Shared ReadOnly Property Text_SecretStar() As String
            Get
                Return ResourceManager.GetString("Text_SecretStar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Position.
        '''</summary>
        Friend Shared ReadOnly Property Text_StartPosition() As String
            Get
                Return ResourceManager.GetString("Text_StartPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Toxic Haze.
        '''</summary>
        Friend Shared ReadOnly Property Text_ToxicHaze() As String
            Get
                Return ResourceManager.GetString("Text_ToxicHaze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend Shared ReadOnly Property Text_Unknown() As String
            Get
                Return ResourceManager.GetString("Text_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} of {1} used / {2} left.
        '''</summary>
        Friend Shared ReadOnly Property Text_UsedOfMaxLeft() As String
            Get
                Return ResourceManager.GetString("Text_UsedOfMaxLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Water.
        '''</summary>
        Friend Shared ReadOnly Property Text_Water() As String
            Get
                Return ResourceManager.GetString("Text_Water", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reload ROM.
        '''</summary>
        Friend Shared ReadOnly Property WarningBox_RomChanged_ReloadRom() As String
            Get
                Return ResourceManager.GetString("WarningBox_RomChanged_ReloadRom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The ROM was changed by an external program. To reload the ROM click on &apos;Reload ROM&apos;..
        '''</summary>
        Friend Shared ReadOnly Property WarningBox_RomChanged_Text() As String
            Get
                Return ResourceManager.GetString("WarningBox_RomChanged_Text", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
