'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")>  _
Partial Public NotInheritable Class AreaEditorSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As AreaEditorSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New AreaEditorSettings()),AreaEditorSettings)
    
    Public Shared ReadOnly Property [Default]() As AreaEditorSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("ORBIT")>  _
    Public Property DefaultCameraMode() As Global.OpenGLCamera.CameraMode
        Get
            Return CType(Me("DefaultCameraMode"),Global.OpenGLCamera.CameraMode)
        End Get
        Set
            Me("DefaultCameraMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Normal")>  _
    Public Property DefaultWindowMode() As Global.System.Windows.Forms.FormWindowState
        Get
            Return CType(Me("DefaultWindowMode"),Global.System.Windows.Forms.FormWindowState)
        End Get
        Set
            Me("DefaultWindowMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property RibbonControlExpanded() As Boolean
        Get
            Return CType(Me("RibbonControlExpanded"),Boolean)
        End Get
        Set
            Me("RibbonControlExpanded") = value
        End Set
    End Property
End Class
