'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")>  _
Partial Public NotInheritable Class GeneralSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As GeneralSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New GeneralSettings()),GeneralSettings)
    
    Public Shared ReadOnly Property [Default]() As GeneralSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AutoUpdates() As Boolean
        Get
            Return CType(Me("AutoUpdates"),Boolean)
        End Get
        Set
            Me("AutoUpdates") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property IntegerValueMode() As Integer
        Get
            Return CType(Me("IntegerValueMode"),Integer)
        End Get
        Set
            Me("IntegerValueMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property EmulatorPath() As String
        Get
            Return CType(Me("EmulatorPath"),String)
        End Get
        Set
            Me("EmulatorPath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
    Public Property ActionIfUpdatePatches() As Global.System.Windows.Forms.DialogResult
        Get
            Return CType(Me("ActionIfUpdatePatches"),Global.System.Windows.Forms.DialogResult)
        End Get
        Set
            Me("ActionIfUpdatePatches") = value
        End Set
    End Property
End Class
