'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")>  _
Partial Public NotInheritable Class StyleManagerSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As StyleManagerSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New StyleManagerSettings()),StyleManagerSettings)
    
    Public Shared ReadOnly Property [Default]() As StyleManagerSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AlwaysKeepBlueColors() As Boolean
        Get
            Return CType(Me("AlwaysKeepBlueColors"),Boolean)
        End Get
        Set
            Me("AlwaysKeepBlueColors") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White, #80397B")>  _
    Public Property MetroColorParams() As Global.DevComponents.DotNetBar.Metro.ColorTables.MetroColorGeneratorParameters
        Get
            Return CType(Me("MetroColorParams"),Global.DevComponents.DotNetBar.Metro.ColorTables.MetroColorGeneratorParameters)
        End Get
        Set
            Me("MetroColorParams") = value
        End Set
    End Property
End Class
